export const SET_USUARIO_LOGADO = 'AUTH/SET_USUARIO_LOGADO';
export const SET_TOKEN = 'AUTH/SET_TOKEN';
export const SET_AUTORIDADE_USUARIO = 'AUTH/SET_AUTORIDADE_USUARIO';
export const SET_EMPRESA_VINCULADA = 'AUTH/SET_EMPRESA_VINCULADA';
export const SET_EMPRESA_CADASTRO = 'AUTH/SET_EMPRESA_CADASTRO';